In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/melbourne-housing-snapshot/melb_data.csv

## Avvalgi amaliyotda `GitHub`ga yuklangan `melb_data.csv` faylni `df` ga chaqirib oling

In [5]:
#Javobingizni shu yerga yozing
import pandas as pd
df = pd.read_csv("/kaggle/input/melbourne-housing-snapshot/melb_data.csv")
df.head()
# githubda bor fayl ammo uni o'qiy olmadi shuning uchun kaggleni o'zidagi fayni o'qitdim
# https://github.com/Azamat2023/Data-science-and-AI/blob/master/melb_data.csv guthubdagi fayl joylashuvu

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [ ]:
# Mening javobim
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/blob/main/melb_data.csv?raw=true")
df.head()

Yuqoridagi Dataframe Melburn shahri uchun sotuvdagi uylar haqida m'lumotlarni jamlagan.

Quyida jadvalning ba'zi sutunlari tarjimasi berilgan (qolganini o'zingiz Google yordamida tarjima qilishingiz mumkin):
- `Room` - xonalar soni
- `Type` - uyning turi (h - villa/kottej/hovli; u - kvartira; t - shahardagi hovli)
- `Price` - narx
- `Bathroom` - tualet-vanna
- `Landsize` - yerning maydoni (hovli uchun)
- `BuildingArea` - Bino qurilgan yerning maydoni
- `YearBuilt` - qurilgan yili
- `Lattitude` va `Longitude` - GPS kordinatalar
- `Regionname` - Region

# ðŸ”º DIQQAT! 
#### **Agar alohida aytilmagan bo'lsa, `df`ga kiritilgan o'zgartirishlarni saqlamang (`inplace=False`)**

## 1-VAZIFA. `df` dagi barcha ustunlardagi`NaN` qiymatlar sonini chiqaring

In [6]:
#Javobingizni shu yerga yozing
df.isna().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

## 2-VAZIFA. `df` barcha `NaN` qiymatlarni 0 bilan almashtiring

In [7]:
#Javobingizni shu yerga yozing
df.fillna(0).head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,0.0,0.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,0.0,0.0,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

## 3-VAZIFA. Quyidagi 2 ustun uchun o'rta qiymatlarni hisoblang:
- BuildingArea
- YearBuilt (**butun son qaytishi kerak**)

In [13]:
#Javobingizni shu yerga yozing
print(df['BuildingArea'].mean())

151.96764988779805

In [14]:
print(int(df['YearBuilt'].mean()))

1964

**To'g'ri javob:**

In [ ]:
print(df['BuildingArea'].mean())
print(int(df['YearBuilt'].mean()))

## 4-VAZIFA: `BuildingArea` va `YearBuilt` ustunlaridagi `NaN` qiymatlarni shu sutun uchun o'rta qiymatlar bilan almashtiring
**DIQQAT!** `YearBuilt` ustuni qiymatlari butun son bo'lishi kerak

In [17]:
#Javobingizni shu yerga yozing
BA = df['BuildingArea'].mean()
YA = int(df['YearBuilt'].mean())
df.fillna({'BuildingArea':BA, 'YearBuilt':YA})

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,151.96765,1964.0,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.00000,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.00000,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,151.96765,1964.0,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.00000,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,151.96765,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.00000,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,151.96765,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.00000,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.00000,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

**To'g'ri javob:**

In [ ]:
df.fillna({'BuildingArea':df['BuildingArea'].mean(), 'YearBuilt':int(df['YearBuilt'].mean())})

## 5-VAZIFA. `.groupby()`
Ustun uchun o'rta qiymat har doim ham aniq bo'lavermaydi. Keling avval `YearBuilt` ustuni uchun aniqroq qiymat topishga harakat qilamiz. 

Buning uchun `Regionname` ustuni qiymatlaridan foydalanishimiz mumkin, ya'ni bir Regiondagi binolar tahminan bir hil yillarda qurilgan deb tahmin qilsak bo'ladi.

### 5.1 `.groupby()` yordamida `df` qiymatlarini `Regionname` ustuni bo'yicha guruhlang va `YaerBuilt` ustuni uchun o'rta qiymatni hisoblang.

In [19]:
#Javobingizni shu yerga yozing
df.groupby('Regionname').YearBuilt.mean(numeric_only=True).astype(int)

Regionname
Eastern Metropolitan          1971
Eastern Victoria              1984
Northern Metropolitan         1962
Northern Victoria             1986
South-Eastern Metropolitan    1976
Southern Metropolitan         1960
Western Metropolitan          1968
Western Victoria              1982
Name: YearBuilt, dtype: int64

**To'g'ri javob:**

In [ ]:
df.groupby(['Regionname']).YearBuilt.mean().astype(int)

### 5.2. `df` `YearBuilt` ustunidagi `NaN` qiymatlarni yuqoridagi qiymatlar bilan almashtiring.
`df[df.Regionname='Eastern Metropolitan']=...`

Har bir `Regionname` uchun qiymatlarni bittalab kiritmaslik uchun for siklidan foydalanishingiz mumkin.

In [20]:
#Javobingizni shu yerga yozing
groups = df.groupby(['Regionname']).YearBuilt.mean() # Bu Series obyekti
for idx in groups.index:
   df[df.Regionname==idx] = df[df.Regionname==idx].fillna({'YearBuilt':groups[idx]})

**To'g'ri javob**

In [ ]:
groups = df.groupby(['Regionname']).YearBuilt.mean() # Bu Series obyekti
for idx in groups.index:
   df[df.Regionname==idx] = df[df.Regionname==idx].fillna({'YearBuilt':groups[idx]})

### `YearBuilt` uchun yana ham aniqroq o'rta qiymat hisoblashning qanday yo'lini taklif qilgan bo'lar edingiz?

## 6-VAZIFA. `BuildingArea` ustunidagi `NaN` qiymatlarni to'ldiramiz
`BuildingArea` bino qurilgan yerning maydonini bildiradi. Bu qiymatlarni tahmin qilish uchun qaysi ustun qiymatlaridan foydalanish to'g'ri deb hisoblaysiz?

In [31]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,1962.764286,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.000000,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.000000,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,1962.764286,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.000000,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

### 6.1 `df`ni xonalar soni bo'yicha o'rta qiymat olib ko'ring

In [25]:
#Javobingizni shu yerga yozing
df.groupby('Rooms').mean(numeric_only=True)

,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
Rooms,,,,,,,,,,,,
1,4.338245e+05,5.939207,3107.058737,1.029369,1.007342,0.883481,384.681351,52.618506,1971.419192,-37.822123,144.984649,8699.651982
2,7.750812e+05,7.727659,3101.450110,2.016996,1.137336,1.129210,421.164748,92.872142,1965.793338,-37.813112,144.989711,7802.574836
3,1.076081e+06,11.003690,3099.933175,2.984696,1.473219,1.697881,597.700731,139.147184,1963.846119,-37.802929,144.987706,7311.337018
4,1.445282e+06,12.149665,3118.688616,3.921503,2.039062,2.062221,639.727679,208.965073,1964.004481,-37.813326,145.012175,7093.617560
5,1.870260e+06,11.778523,3117.986577,4.875839,2.686242,2.310403,798.505034,405.607347,1964.692956,-37.814517,145.033244,7051.510067
6,1.849366e+06,12.685075,3121.402985,5.820896,2.820896,2.582090,841.462687,278.513889,1960.707592,-37.808151,145.034099,6668.865672
7,1.920700e+06,9.560000,3095.700000,6.600000,2.900000,2.600000,1089.700000,340.423333,1974.681184,-37.792333,145.033313,6874.300000
8,1.602750e+06,10.912500,3095.875000,7.125000,4.125000,3.375000,843.875000,256.000000,1965.583968,-37.799385,145.014315,6085.375000
10,9.000000e+05,12.100000,3083.000000,10.000000,3.000000,2.000000,313.000000,NaN,2006.000000,-37.710980,145.053810,10175.000000

### 6.2 Xonalar va uy turi bo'yicha o'rta qiymatni olib ko'ring.

In [26]:
#Javobingizni shu yerga yozing
df.groupby(['Rooms', 'Type']).mean(numeric_only=True)

                   Price   Distance     Postcode   Bedroom2  Bathroom  \
Rooms Type
1     h     8.668655e+05   7.068966  3087.224138   1.103448  1.068966
      t     5.927045e+05   6.981818  3092.000000   1.090909  1.000000
      u     3.899289e+05   5.813399  3109.209150   1.021242  1.001634
2     h     1.017238e+06   7.578255  3090.577253   2.029328  1.081545
      t     7.101585e+05   8.941379  3087.326019   2.003135  1.338558
      u     6.104905e+05   7.635318  3111.655101   2.010357  1.144485
3     h     1.109233e+06  11.253572  3098.533847   2.987919  1.407623
      t     9.847087e+05   9.974563  3103.050874   2.977742  1.918919
      u     8.505963e+05   9.778936  3110.481153   2.960089  1.549889
4     h     1.462283e+06  12.204211  3118.750099   3.922130  2.017084
      t     1.217092e+06  11.444667  3121.360000   3.906667  2.400000
      u     1.037476e+06  10.647619  3092.238095   3.952381  2.095238
5     h     1.877327e+06  11.785787  3118.351946   4.874788  2.690355
      t     1.035000e+06  10.920000  3074.800000   5.000000  2.200000
6     h     1.869508e+06  12.753030  3123.060606   5.848485  2.833333
      u     5.200000e+05   8.200000  3012.000000   4.000000  2.000000
7     h     1.920700e+06   9.560000  3095.700000   6.600000  2.900000
8     h     1.510286e+06  11.357143  3101.285714   7.571429  4.428571
      u     2.250000e+06   7.800000  3058.000000   4.000000  2.000000
10    h     9.000000e+05  12.100000  3083.000000  10.000000  3.000000

                 Car     Landsize  BuildingArea    YearBuilt  Lattitude  \
Rooms Type
1     h     0.807018   297.206897     85.400000  1958.792275 -37.787817
      t     0.636364   193.181818     70.714286  1982.844805 -37.833014
      u     0.895082   396.413399     50.181433  1972.410498 -37.825178
2     h     1.142128   337.489986    103.238231  1949.520243 -37.802747
      t     1.188088   261.595611    120.103632  1985.335853 -37.794179
      u     1.110306   508.104091     80.852963  1974.346277 -37.823744
3     h     1.719195   651.883149    141.511957  1959.273866 -37.798971
      t     1.691574   279.448331    137.620152  1988.640114 -37.819691
      u     1.481153   464.776053    117.998941  1977.939162 -37.821690
4     h     2.077994   661.470004    210.265265  1962.256419 -37.811324
      t     1.826667   326.413333    194.634184  1991.175277 -37.845255
      u     1.857143   271.714286    161.400000  1979.445080 -37.825299
5     h     2.314721   803.275804    407.745961  1964.448370 -37.814808
      t     1.800000   234.600000    159.666667  1993.603019 -37.780148
6     h     2.606061   854.212121    281.585714  1960.566798 -37.808138
      u     1.000000     0.000000    171.000000  1970.000000 -37.809000
7     h     2.600000  1089.700000    340.423333  1974.681184 -37.792333
8     h     3.285714   824.000000    256.000000  1965.986780 -37.806197
      u     4.000000   983.000000           NaN  1962.764286 -37.751700
10    h     2.000000   313.000000           NaN  2006.000000 -37.710980

            Longtitude  Propertycount
Rooms Type
1     h     144.964712    7283.051724
      t     144.988266    7195.454545
      u     144.986473    8860.941176
2     h     144.980881    7317.441345
      t     144.979010    7545.489028
      u     144.997872    8196.270844
3     h     144.984934    7349.872110
      t     144.998826    6996.322734
      u     145.001703    7340.465632
4     h     145.011239    7121.709972
      t     145.024198    6545.193333
      u     145.038477    7643.857143
5     h     145.033487    7052.620981
      t     145.004502    6920.200000
6     h     145.036606    6693.272727
      u     144.868600    5058.000000
7     h     145.033313    6874.300000
8     h     145.020660    5354.142857
      u     144.969900   11204.000000
10    h     145.053810   10175.000000

### 6.3 Ahamiyat bering, 10 xonalik uylar uchun o'rta qiymat chiqmayapti. Bu nimadan dalolat beradi? Jami 10 xonalik uylar nechta? Ular bilan qanday yo'l tutishni maslahat berasiz?

In [32]:
#Javobingizni shu yerga yozing
df['Rooms'].unique()
# bu koddan ko'rinib turibdiki 9 xonali uylar yo'q ekan

array([ 2,  3,  4,  1,  6,  5,  8,  7, 10])

### 6.4 `BuildingArea` ustunidagi mavjud `NaN` qiymatlarni o'zingiz to'g'ri deb bilgan usul bilan to'ldiring.

In [33]:
df.fillna({'BuildingArea':df['BuildingArea'].mean()})

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,151.96765,1962.764286,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.00000,1900.000000,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.00000,1900.000000,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,151.96765,1962.764286,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.00000,2014.000000,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,151.96765,1981.000000,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.00000,1995.000000,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,151.96765,1997.000000,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.00000,1920.000000,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.00000,1920.000000,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

### 7-VAZIFA. Yuqoridagi vazifalardan so'ng, bizda faqatgina `CouncilArea` ustunida `NaN` qiymatlar qolishi kerak xolos.
**Bu ustundagi `NaN` qiymatlarni avvalgi qatordagi qiymatlar bilan to'ldirib keting. Natijani saqlab qoling**

In [35]:
df[df.CouncilArea.isna()].fillna(method='bfill')

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
7584,Brighton East,7 Roberts Ct,3,h,1270000.0,VB,Ray,20/05/2017,10.7,3187.0,...,1.0,3.0,724.0,187.0,1960.523777,NaN,-37.92910,145.02970,Southern Metropolitan,6938.0
10797,Reservoir,48 Crevelli St,3,h,526250.0,SP,Barry,8/07/2017,12.0,3073.0,...,1.0,1.0,308.0,187.0,1962.764286,NaN,-37.72828,145.03033,Northern Metropolitan,21650.0
12213,Aberfeldie,1 Alma St,4,h,1436000.0,S,Brad,3/09/2017,7.5,3040.0,...,3.0,3.0,511.0,187.0,1922.000000,NaN,-37.75788,144.90487,Western Metropolitan,1543.0
12214,Albion,40 Ridley St,5,h,905000.0,S,hockingstuart,3/09/2017,10.5,3020.0,...,2.0,3.0,732.0,148.0,1925.000000,NaN,-37.78345,144.82295,Western Metropolitan,2185.0
12215,Alphington,22 Harker St,4,h,1680000.0,S,Love,3/09/2017,5.7,3078.0,...,3.0,2.0,720.0,148.0,1962.764286,NaN,-37.77928,145.02993,Northern Metropolitan,2211.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,133.0,1981.000000,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.000000,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,157.0,1997.000000,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.000000,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.000000,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

## YAKUNIY JADVAL
Ahamiyat bering, yakuniy jadvalda `NaN` qiymatlar bo'lmasligi kerak.

In [36]:
df.isnull().sum()
# man inplace = True qilmadim shuning uchun o'zgarmadi asl data freym

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt           0
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64